### ISSUE TITLE
Vaadin 14.9.x breaks Enhanced Crud

### ISSUE THREAD

**Issue by TatuLund** [vaadin-component-factory/enhanced-crud#1]
java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'vaadin-crud' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
   at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:151)
   at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:223)
   at com.vaadin.flow.component.polymertemplate.TemplateInitializer.(TemplateInitializer.java:96)
   at com.vaadin.flow.component.polymertemplate.PolymerTemplate.(PolymerTemplate.java:91tfactory.enhancedcrud.Crud.(Crud.java:174)
   at com.vaadin.componentfactory.enhancedcrud.Crud.(Crud.java:114)
   at com.linxa.connect.mtrftrsetting.VMtrFtrSettings.createCrud(VMtrFtrSettings.java:138)
   at com.linxa.connect.mtrftrsetting.VMtrFtrSettings.start(VMtrFtrSettings.java:106)
6)
   at com.vaadin.componentfactory.enhancedcrud.Crud.(Crud.java:174)
   at com.vaadin.componentfactory.enhancedcrud.Crud.(Crud.java:114)
   at com.linxa.connect.mtrftrsetting.VMtrFtrSettings.createCrud(VMtrFtrSettings.java:138)
   at com.linxa.connect.mtrftrsetting.VMtrFtrSettings.start(VMtrFtrSettings.java:106)

**Comment by TatuLund** [comment]
Related to https://github.com/vaadin-component-factory/autocomplete/issues/22

**Comment by TatuLund** [comment]
Fixed in version 1.3.0
